//Ejercicio 2. Elementos
Adaptar el DTD para hacer que no haya errores de validacion en el XML. No tocar el
XML.

//Elementos
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE elementos [
 <!ELEMENT elementos (pcdata*, any+, vacio)>
 <!ELEMENT pcdata (#PCDATA)>
 <!ELEMENT any ANY>
 <!ELEMENT vacío EMPTY>
]>

<elementos>
 <any/>
 <vacio/>
</elementos>




//Ciudades

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ciudades [
 <!ELEMENT ciudades (ciudad)*>
 <!ELEMENT ciudad (nombre, capital?)>        // Puede tambien ponerse * en la palabra capital pero no es su caso por lo que nos pide en el xml.
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT capital EMPTY>
]>
<ciudades>
 <ciudad>
 <nombre>Buenos Aires</nombre>
 <capital/>
 </ciudad>
 <ciudad>
 <nombre>Liverpool</nombre>
 </ciudad>
 <ciudad>
 <nombre>Osaka</nombre>
 </ciudad>
 <ciudad>
 <nombre>Oslo</nombre>
 <capital/>
 </ciudad>
</ciudades>




//Socios

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE socios [
 <!ELEMENT socios (socio)*>
 <!ELEMENT socio (numero?, clave?, nombre, edad?)>          //+ Es uno o mas.
 <!ELEMENT  numero (#PCDATA)>
 <!ELEMENT clave  (#PCDATA)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT  edad (#PCDATA)>
]>

<socios>
 <socio>
 <nombre>Ana</nombre>
 <edad>21</edad>
 </socio>
 <socio>
 <numero>598</numero>
 <nombre>Iker</nombre>
 <edad>19</edad>
 </socio>
 <socio>
 <clave>hY75Du</clave>
 <nombre>Iker</nombre>
 </socio>
</socios>


// Ejercicio 3. Atributos
Corregir los errores en el XML para que sea un documento válido. No tocar el DTD.

Formas
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formas [
 <!ELEMENT formas (cuadrado, triangulo, circulo, otra)>
 <!ELEMENT cuadrado (#PCDATA)>
 <!ATTLIST cuadrado lados CDATA #REQUIRED>
 <!ELEMENT triangulo (#PCDATA)>
 <!ATTLIST triangulo lados CDATA #REQUIRED>
 <!ELEMENT circulo (#PCDATA)>
 <!ELEMENT otra EMPTY>
 <!ATTLIST otra lados CDATA #REQUIRED>
]>

<formas>
 <cuadrado lados="4">tablero</cuadrado>
 <circulo>anilla</circulo>
 <triangulo lados= 3 señal> </triangulo>
 <otra lados="7"/>
</formas>



Empresas
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresas [
 <!ELEMENT empresas (empresa)*>
 <!ELEMENT empresa EMPTY>
 <!ATTLIST empresa nombre CDATA #REQUIRED>
 <!ATTLIST empresa fecha_de_fundacion CDATA #IMPLIED>
]>
<empresas>
 <empresa  nombre =Apple fecha_de_fundacion="1976"Apple/>
 <empresa nombre =Google/>
  <empresa fecha_de_fundacion="1975">Microsoft</empresa>
</empresas>
// Este ejercicio de arriba tengo que mirarlo para tener la correcion bien. 




//Artículos
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE articulos [
 <!ELEMENT articulos (articulo)+>
 <!ELEMENT articulo (#PCDATA)>
 <!ATTLIST articulo color CDATA #FIXED "rojo">
]>
<articulos>
 <articulo  color="rojo">"bolígrafo" </articulo>
 <articulo>"cuaderno"</articulo>
 <articulo color="amarillo">"rotulador"</articulo>
</articulos>


// Hay que realizar geografía y pizza.
//Geografía
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE geografia [
 <!ELEMENT geografia (paises, ciudades)>
 <!ELEMENT paises (pais)*>
 <!ELEMENT pais (#PCDATA)>
 <!ATTLIST pais codpais ID #REQUIRED>
 <!ELEMENT ciudades (ciudad)*>
 <!ELEMENT ciudad (#PCDATA)>
 <!ATTLIST ciudad pais IDREF #IMPLIED>
]>
<geografia>
 <paises>
 <pais codpais="1">Argentina</pais>
 <pais codpais="2">Austria</pais>
 <pais codpais="3">Japón</pais>
 <pais codpais="4">Noruega</pais>
 </paises>
 <ciudades>
 <ciudad pais="3">Osaka</ciudad>
 <ciudad>Oslo</ciudad>
 <ciudad pais="">Sevilla</ciudad>
 <ciudad pais="3">Tokio</ciudad>
 <ciudad pais="2">Viena</ciudad>
 </ciudades>
</geografia>




//Ejercicio 4. Atributos
Adaptar el DTD para hacer que no haya errores de validación en el XML. No tocar el
XML.

//Declaraciones
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE declaraciones [
 <!ELEMENT declaraciones (constante | tipo_de_dato | variable)*>    // La separación entre barra o tuberías es que puede solo puede aparecer uno. 
 <!ELEMENT consonante (#PCDATA)>
 <!ATTLIST consonante valor CDATA #REQUIRED>
 <!ELEMENT tipo_de_dato (#PCDATA)>
 <!ELEMENT variable (#PCDATA)>
 <!ATTLIST variable tipo CDATA #IMPLIED>
]>

<declaraciones>
 <constante valor="3.141592">PI</constante>
 <variable tipo="real">radio</variable>
 <variable>area</variable>
 <variable>longitud</variable>
</declaraciones>





